In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("../dataset/preprocess/eda_pre.csv", header=None)
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,1,Male,27,Software Engineer,"6,1",6,42,6,Overweight,126/83,77,4200,NaN,126,83,Normal
1,2,Male,28,Doctor,"6,2",6,60,8,Normal,125/80,75,10000,NaN,125,80,Normal
2,3,Male,28,Doctor,"6,2",6,60,8,Normal,125/80,75,10000,NaN,125,80,Normal
3,4,Male,28,Sales Representative,"5,9",4,30,8,Obese,140/90,85,3000,Sleep Apnea,140,90,Grade 1 hypertension
4,5,Male,28,Sales Representative,"5,9",4,30,8,Obese,140/90,85,3000,Sleep Apnea,140,90,Grade 1 hypertension

In [4]:
columns = [
    "Person_ID",
    "Gender",
    "Age",
    "Occupation",
    "Sleep_Duration",
    "Quality_of_Sleep",
    "Physical_Activity_Level",
    "Stress_Level",
    "BMI_Category",
    "Blood_Pressure",
    "Heart_Rate",
    "Daily_Steps",
    "Sleep_Disorder",
    "Systolic",
    "Diastolic",
    "Blood_Pressure_Category"
]

df.columns = columns

df.head()

,Person_ID,Gender,Age,Occupation,Sleep_Duration,Quality_of_Sleep,Physical_Activity_Level,Stress_Level,BMI_Category,Blood_Pressure,Heart_Rate,Daily_Steps,Sleep_Disorder,Systolic,Diastolic,Blood_Pressure_Category
0,1,Male,27,Software Engineer,"6,1",6,42,6,Overweight,126/83,77,4200,NaN,126,83,Normal
1,2,Male,28,Doctor,"6,2",6,60,8,Normal,125/80,75,10000,NaN,125,80,Normal
2,3,Male,28,Doctor,"6,2",6,60,8,Normal,125/80,75,10000,NaN,125,80,Normal
3,4,Male,28,Sales Representative,"5,9",4,30,8,Obese,140/90,85,3000,Sleep Apnea,140,90,Grade 1 hypertension
4,5,Male,28,Sales Representative,"5,9",4,30,8,Obese,140/90,85,3000,Sleep Apnea,140,90,Grade 1 hypertension

In [5]:
df["Sleep_Duration"] = df["Sleep_Duration"].astype(str).str.replace(",", ".")
df["Sleep_Duration"] = df["Sleep_Duration"].astype(float)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Person_ID                374 non-null    int64
 1   Gender                   374 non-null    object
 2   Age                      374 non-null    int64
 3   Occupation               374 non-null    object
 4   Sleep_Duration           374 non-null    float64
 5   Quality_of_Sleep         374 non-null    int64
 6   Physical_Activity_Level  374 non-null    int64
 7   Stress_Level             374 non-null    int64
 8   BMI_Category             374 non-null    object
 9   Blood_Pressure           374 non-null    object
 10  Heart_Rate               374 non-null    int64
 11  Daily_Steps              374 non-null    int64
 12  Sleep_Disorder           155 non-null    object
 13  Systolic                 374 non-null    int64
 14  Diastolic                374 non-null    int64
 15  Blood_Pressure_Category  374 non-null    object
dtypes: float64(1), int64(9), object(6)
memory usage: 46.9+ KB

In [7]:
num_cols = [
    "Age",
    "Quality_of_Sleep",
    "Physical_Activity_Level",
    "Stress_Level",
    "Heart_Rate",
    "Daily_Steps",
    "Systolic",
    "Diastolic"
]

for col in num_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [8]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Person_ID                374 non-null    int64
 1   Gender                   374 non-null    object
 2   Age                      374 non-null    int64
 3   Occupation               374 non-null    object
 4   Sleep_Duration           374 non-null    float64
 5   Quality_of_Sleep         374 non-null    int64
 6   Physical_Activity_Level  374 non-null    int64
 7   Stress_Level             374 non-null    int64
 8   BMI_Category             374 non-null    object
 9   Blood_Pressure           374 non-null    object
 10  Heart_Rate               374 non-null    int64
 11  Daily_Steps              374 non-null    int64
 12  Sleep_Disorder           155 non-null    object
 13  Systolic                 374 non-null    int64
 14  Diastolic                374 non-null    int64
 15  Blood_Pressure_Category  374 non-null    object
dtypes: float64(1), int64(9), object(6)
memory usage: 46.9+ KB

Person_ID                    0
Gender                       0
Age                          0
Occupation                   0
Sleep_Duration               0
Quality_of_Sleep             0
Physical_Activity_Level      0
Stress_Level                 0
BMI_Category                 0
Blood_Pressure               0
Heart_Rate                   0
Daily_Steps                  0
Sleep_Disorder             219
Systolic                     0
Diastolic                    0
Blood_Pressure_Category      0
dtype: int64

In [9]:
df["Sleep_Disorder"] = df["Sleep_Disorder"].fillna("None")

In [10]:
df.isnull().sum()

Person_ID                  0
Gender                     0
Age                        0
Occupation                 0
Sleep_Duration             0
Quality_of_Sleep           0
Physical_Activity_Level    0
Stress_Level               0
BMI_Category               0
Blood_Pressure             0
Heart_Rate                 0
Daily_Steps                0
Sleep_Disorder             0
Systolic                   0
Diastolic                  0
Blood_Pressure_Category    0
dtype: int64

In [12]:
df = df.drop(columns=["Person_ID", "Blood_Pressure","Diastolic","Blood_Pressure_Category"])

In [13]:
text_cols = ["Gender", "Occupation", "BMI_Category", "Sleep_Disorder"]

for col in text_cols:
    df[col] = df[col].str.strip()

In [14]:
df.head(5)

,Gender,Age,Occupation,Sleep_Duration,Quality_of_Sleep,Physical_Activity_Level,Stress_Level,BMI_Category,Heart_Rate,Daily_Steps,Sleep_Disorder,Systolic
0,Male,27,Software Engineer,6.1,6,42,6,Overweight,77,4200,None,126
1,Male,28,Doctor,6.2,6,60,8,Normal,75,10000,None,125
2,Male,28,Doctor,6.2,6,60,8,Normal,75,10000,None,125
3,Male,28,Sales Representative,5.9,4,30,8,Obese,85,3000,Sleep Apnea,140
4,Male,28,Sales Representative,5.9,4,30,8,Obese,85,3000,Sleep Apnea,140

In [16]:
df.to_csv("../dataset/preprocess/sleep_health_clean.csv", index=False)

print("Done")

Done